FROM nvidia/cuda:10.0-base-ubuntu18.04 

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
      build-essential \
        cuda-command-line-tools-10-0 \
        cuda-cublas-10-0 \
        #cuda-cudart-dev-10-0 \
        cuda-cufft-10-0 \
        cuda-curand-10-0 \
        cuda-cusolver-10-0 \
        cuda-cusparse-10-0 \
        libcudnn7=7.4.1.5-1+cuda10.0 \
        libcudnn7-dev=7.4.1.5-1+cuda10.0 \
        curl \
        #libcurl3-dev \
        libfreetype6-dev \
        libhdf5-serial-dev \
        libpng-dev \
        libzmq3-dev \
        pkg-config \
        rsync \
        software-properties-common \
        python3 \
        python3-pip \
        python3-dev \
        unzip \
        wget \
        libtesseract-dev \
        tesseract-ocr \
        poppler-utils \
        libglib2.0 \
        libsm6 \
        libxext6 \
        && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN cd /usr/local/bin && ln -s /usr/bin/python3 python && ln -s /usr/bin/pip3 pip
ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:/usr/local/cuda/lib64:$LD_LIBRARY_PATH

# Install python packages
COPY requirements.txt /install
WORKDIR /install
RUN pip install -r requirements.txt

WORKDIR /install
RUN wget https://github.com/cocodataset/cocoapi/archive/master.zip -O cocoapi.zip
RUN wget https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-linux-x86_64.zip -O protobuf.zip
RUN wget https://github.com/tensorflow/models/archive/59f7e80ac8ad54913663a4b63ddf5a3db3689648.zip -O tensorflow-models.zip

RUN unzip cocoapi.zip
RUN unzip protobuf.zip -d ./protobuf
RUN unzip tensorflow-models.zip -d ./tensorflow-models

RUN mkdir /oss

# Install cocoapi
RUN mv /install/cocoapi-master /oss/cocoapi
WORKDIR /oss/cocoapi/PythonAPI
RUN python setup.py install

# Install tensorflow object detection
RUN mv /install/tensorflow-models/models-59f7e80ac8ad54913663a4b63ddf5a3db3689648 /oss/models
RUN mv /install/protobuf /oss
WORKDIR /oss/models/research
RUN /oss/protobuf/bin/protoc ./object_detection/protos/*.proto --python_out=.
RUN python setup.py install

# Remove temp and cache folders
RUN rm -rf /var/lib/apt/lists/* && rm -rf /var/cache/apt/* && rm -rf /root/.cache/* && rm -rf /install
