sudo: required

services:
  - docker

before_install:
  - docker build -t computervision:ubuntu18-cuda9 -f ubuntu18-cuda9.Dockerfile .

script:
  - docker run computervision:ubuntu18-cuda9 /bin/bash -c "pdftoppm -v; pip list; java -version; javac -version"
  - docker push nishantagarwal/computervision:ubuntu18-cuda9
