sudo: required

services:
  - docker

before_install:
  - docker build -t computervision:ubuntu18-python36 -f ubuntu18-python36.Dockerfile .

script:
  - docker run computervision:ubuntu18-python36 /bin/bash -c "pdftoppm -v; pip list; java -version; javac -version"
  - docker push nishantagarwal/computervision:ubuntu18-python36
