sudo: required

services:
  - docker

before_install:
  - docker build -t nishantagarwal/computervision:ubuntu18-cuda9 -f ubuntu18-cuda9.Dockerfile .

script:
  - docker run nishantagarwal/computervision:ubuntu18-cuda9 /bin/bash -c "pdftoppm -v; pip list; java -version; javac -version"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nishantagarwal/computervision:ubuntu18-cuda9
